### ISSUE TITLE
Upgrade to the latest SpeziLLM release

### ISSUE THREAD

**Issue by Supereg** [StanfordSpezi/SpeziFHIR#15]
### Problem

Currently, the SpeziFHIR package still depends on the legacy SpeziML `0.3.0` release. Since then, SpeziML was renamed to SpeziLLM and its version was bumped to `0.5.0`. Due to the changed interface, SpeziFHIR is currently incompatible with the latest release of SpeziLLM.

### Solution

There is some work required within SpeziLLM to bring back the previous functionality that SpeziFHIR uses. Once, this is done, SpeziFHIR can be upgraded to the latest releases of the Spezi framework ecosystem. 

### Additional context

This is currently a blocker to use SpeziFHIR with other Spezi releases which recently upgraded to the latest 1.0 releases.
As SpeziFHIR depends on a previous release of Spezi (SpeziLLM as well) it is incompatible to use with the latest version of packages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
Done by https://github.com/StanfordSpezi/SpeziFHIR/pull/17 and https://github.com/StanfordBDHG/LLMonFHIR/pull/44.
