### ISSUE TITLE
FHIRStore Crash When Using CloudKit/CoreData

### ISSUE THREAD

**Issue by advatar** [StanfordSpezi/SpeziFHIR#16]
### Description

When collecting samples like this:

```
private var healthKit: HealthKit {
        HealthKit {
            CollectSamples(
                [
                    HKClinicalType(.allergyRecord),
                    HKClinicalType(.clinicalNoteRecord),
                    HKClinicalType(.conditionRecord),
                    HKClinicalType(.coverageRecord),
                    HKClinicalType(.immunizationRecord),
                    HKClinicalType(.labResultRecord),
                    HKClinicalType(.medicationRecord),
                    HKClinicalType(.procedureRecord),
                    HKClinicalType(.vitalSignRecord)
                ],
                predicate: HKQuery.predicateForSamples(
                    withStart: Date.distantPast,
                    end: nil,
                    options: .strictEndDate
                ),
                deliverySetting: .anchorQuery(saveAnchor: false)
                //deliverySetting: .manual(safeAnchor: false)
            )
        }
    }

```

I often get crashes ending with:

`SwiftUI/FetchCommon.swift:51: Fatal error: Can only invoke this method on the main queue`

The traceback is like:

![image](https://github.com/StanfordSpezi/SpeziFHIR/assets/28670/608b88df-14c6-46a5-b792-c8f50ad295de)

### Reproduction

See above

### Expected behavior

Samples should be collected and added to the FHIRStore without crashing

### Additional context

I am doing something similar to t: [](https://github.com/StanfordBDHG/LLMonFHIR)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@advatar Can you share a minimally reproducible example that we can use to work on fixing the bug together? A very simple iOS app that just contains the necessary code to reproduce the results and only the necessary Stanford dependencies would be great. Ideally you can share it as an GitHub project; that would be perfect!
