### ISSUE TITLE
Complete Concurrency Checking

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziFHIR#19]
### Problem

With [Swift 6 approaching in a few months](https://forums.swift.org/t/swift-6-0-release-process/70220) and [nightly builds already being available](https://forums.swift.org/t/swift-6-0-nightly-development-snapshots/70936) we should ensure that all our packages are working well with all Swift concurrency checks.

### Solution

[Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/) in the Swift Package in a PR and ensure that we don't have any warnings remaining in the packages as we develop new features or fix bugs from now.

The UI Testing App target should also enable [Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/).

The corresponding PR should fix all related warnings when enabling strict concurrency checking.

### Additional context

We should consider adding `SWIFT_TREAT_WARNINGS_AS_ERRORS = YES` to our general workflows to ensure all warnings are flagged as errors during our CI setup.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
As part of fixing any concurrency errors, we should improve FHIRStore to be actor isolated instead of using a locking mechanism as introduced in #21.

**Comment by philippzagar** [comment]
Complete concurrency checking with Swift 6 language mode enabled in: https://github.com/StanfordSpezi/SpeziFHIR/pull/23

However, we did not yet improve the `FHIRStore` to use actor isolation.

**Comment by jdisho** [comment]
I've created #25 to address the actor isolation. Since #23 should have resolved all the concurrency warnings, can we close this issue and continue in #25?

**Comment by philippzagar** [comment]
> I've created #25 to address the actor isolation. Since #23 should have resolved all the concurrency warnings, can we close this issue and continue in #25?

Thanks @jdisho for creating #25! Let's close out this issue and tackle the remaining `FHIRStore` actor isolation in #25!
